stages:
  - name: stage1
    dependencies: ['init']
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input: {stages: init, output: inputpar, unwrap: true}
      step: {$ref: steps.yml#/stepA}
  - name: stage2
    dependencies: ['stage1']
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input: {stages: stage1, output: outputA, unwrap: true}
      step: {$ref: steps.yml#/stepB}
