stages:
  - name: stageA
    dependencies: ['init']
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input_file: {step: init, output: input}
        output_file: '{workdir}/output'
      step: {$ref: steps.yml#/stepA}
  - name: stageB
    dependencies: ['stageA']
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input_file: {stages: stageA, output: outputA}
        output_file: '{workdir}/output'
      step: {$ref: steps.yml#/stepB}