stages:
  - name: map
    dependencies: [init]
    scheduler:
      scheduler_type: multistep-stage
      parameters:
        input: {step: init, output: input, unwrap: true}
      workflow: {$ref: subflow.yml}
      scatter:
        method: zip
        parameters: [input]
  - name: reduce
    dependencies: [map]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input_file: {stages: 'map.[*].stageB', output: outputB}
        output_file: '{workdir}/output'
      step: {$ref: steps.yml#/stepC}