stages:
  - name: produce_ntuple
    dependencies: [init]
    scheduler:
      scheduler_type: multistep-stage
      parameters:
        input_file_PU: {step: init, output: PU_files}
        input_file_noPU: {step: init, output: noPU_files}
        global_tag: {step: init, output: GT}
      workflow: {$ref: workflow_ntuple.yaml}
      batchsize: 5
      scatter:
        method: zip
        parameters: [input_file_PU, input_file_noPU]

  - name: match_lumi
    dependencies: [produce_ntuple]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        lumi_file_PU: {stages: 'produce_ntuple.[*].list_lumi_PU', output: lumi_file}
        lumi_file_noPU: {stages: 'produce_ntuple.[*].list_lumi_noPU', output: lumi_file}
        output_file: '{workdir}/hello.yml'
      step: {$ref: steps.yaml#/match_files}

  - name: test
    dependencies: [match_lumi]
    scheduler:
      scheduler_type: multistep-stage
      parameters:
        input_file: {stages: 'match_lumi', output: MatchedFiles, unwrap: true}
        output_file: '{workdir}/test'
      batchsize: 2
      scatter:
        method: zip
        parameters: [input_file]
      step: {$ref: steps.yaml#/test}